version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextstudy_app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      # 아래의 주석을 해제하면 호스트의 node_modules를 컨테이너에 마운트하지 않음
      - /app/node_modules
